version: '3.8'
services:
  wm-freegpt:
    image: ghcr.io/wm-chatgpt/wm-freegpt:main
    restart: always
    ports:
      - "9800:9800"
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./config.yaml:/app/config.yaml